spring:
    datasource:
      druid:
        url: jdbc:mysql://47.93.58.119:3306/campusdb?serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
        username: xiaohe
        password: 123456
        initial-size: 1
        min-idle: 1
        max-active: 20
    servlet:
      multipart:
        max-file-size: 10MB


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sjiag.Beans

# 上传文件总的最大值


logging:
  level:
    com.sjiag.Dao: trace

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

